#pragma once

enum GameSetting
{
	PLAYER_BASE_HEALTH,
	PLAYER_HEALTH_MULTIPLE,
	PLAYER_HEALTH_ADD,

	PLAYER_BASE_MANA,
	PLAYER_MANA_MULTIPLE,
	PLAYER_MANA_ADD,

	PLAYER_BASE_STAMINA,
	PLAYER_STAMINA_MULTIPLE,
	PLAYER_STAMINA_ADD,

	MONSTER_BASE_HEALTH,
	MONSTER_HEALTH_MULTIPLE,

	MONSTER_BASE_MANA,
	MONSTER_MANA_MULTIPLE,

	MONSTER_BASE_STAMINA,
	MONSTER_STAMINA_MULTIPLE,

	PLAYER_REGEN_RATE_HEALTH,
	PLAYER_REGEN_RATE_MANA,
	PLAYER_REGEN_RATE_STAMINA,

	PLAYER_COMBAT_REGEN_RATE_HEALTH,
	PLAYER_COMBAT_REGEN_RATE_MANA,
	PLAYER_COMBAT_REGEN_RATE_STAMINA,

	MONSTER_REGEN_RATE_HEALTH,
	MONSTER_REGEN_RATE_MANA,
	MONSTER_REGEN_RATE_STAMINA,

	MONSTER_COMBAT_REGEN_RATE_HEALTH,
	MONSTER_COMBAT_REGEN_RATE_MANA,
	MONSTER_COMBAT_REGEN_RATE_STAMINA,

	MONSTER_HEALTH_MOD_EASY,
	MONSTER_HEALTH_MOD_NORMAL,
	MONSTER_HEALTH_MOD_TOUGH,

	MONSTER_HEALTH_MOD_RANK_NORMAL,
	MONSTER_HEALTH_MOD_RANK_MINI_BOSS,
	MONSTER_HEALTH_MOD_RANK_BOSS,

	MONSTER_MANA_MOD_EASY,
	MONSTER_MANA_MOD_NORMAL,
	MONSTER_MANA_MOD_TOUGH,

	MONSTER_MANA_MOD_RANK_NORMAL,
	MONSTER_MANA_MOD_RANK_MINI_BOSS,
	MONSTER_MANA_MOD_RANK_BOSS,

	MONSTER_DELAY_PENALTY,
	MONSTER_MOVE_DELAY,
	MONSTER_MOVE_FLOOR,

	LEVELS_PER_TIER,
	XP_NEEDED_MULTI,

	ACTIVATE_DELAY,
	ACTIVATE_FLOOR,

	NODE_DELAY,
	NODE_XP_GAIN,
	NODE_DIFFICULTY,

	ITEM_BUY_MOD,
	ITEM_SELL_MOD,

	XP_QUEST_MOD,
	XP_KILL_MOD,
	XP_NODE_MOD,

	GOLD_QUEST_MOD,

	CARRY_CAPACITY,

	TOTAL_GAME_SETTINGS,
};

extern const char *GameSettings[];
